### ISSUE TITLE
Image processing

### ISSUE THREAD

**Issue by BUSH222** [BUSH222/cj-The-Expected-Indents#4]
IMAGE PROCESSING
- [x] Initialize image processing class
- [x] Fetch image from flask backend
- [x] Use Pillow to split image into tiles of random height and width
- [x] Create function which selects and places random image tiles
- [x] Create function which handles incorrect guesses and blackens some placed tiles

**Comment by Zike01** [comment]
Use Pillow to split the image into square tiles of random width and height
